# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: fix-byte-order-marker
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-illegal-windows-names
    -   id: check-added-large-files

-   repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v1.0.1
    hooks:
    -   id: clang-format
        files: \.(c|h)$
        args: [--version=20, --style=file, --verbose]
