if("$ENV{CDASH_AUTH_TOKEN}" STREQUAL "")
    message(FATAL_ERROR "CDASH_AUTH_TOKEN environment variable not set")
endif()

if("${CMAKE_C_COMPILER}" STREQUAL "")
    message(FATAL_ERROR "CMAKE_C_COMPILER not set")
endif()

if("${CTEST_SOURCE_DIRECTORY}" STREQUAL "")
    message(FATAL_ERROR "CTEST_SOURCE_DIRECTORY not set")
endif()


set(CTEST_BINARY_DIRECTORY ${CTEST_SOURCE_DIRECTORY}/build)

cmake_host_system_information(RESULT CTEST_SITE QUERY HOSTNAME)
cmake_host_system_information(RESULT CTEST_BUILD_NAME QUERY OS_NAME OS_PLATFORM)
list(APPEND CTEST_BUILD_NAME ${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION})
list(JOIN CTEST_BUILD_NAME "-" CTEST_BUILD_NAME)

list(APPEND CONFIGURE_OPTIONS
    -DENABLE_ASAN:BOOL=ON
    -DENABLE_CLANG_TIDY:BOOL=ON
    -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
    -DCMAKE_BUILD_TYPE:STRING=${CTEST_CONFIGURATION_TYPE}
    -DCLANG_TIDY_WARNINGS_AS_ERRORS:BOOL=${CLANG_TIDY_WARNINGS_AS_ERRORS}
)
list(JOIN CONFIGURE_OPTIONS " " CONFIGURE_OPTIONS_STR)



ctest_start(Continuous)


ctest_configure(OPTIONS "${CONFIGURE_OPTIONS_STR}")


ctest_build()


include("src/MemoryCheck.cmake")
ctest_memcheck()


ctest_submit(
    HTTPHEADER "Authorization: Beare $ENV{CDASH_AUTH_TOKEN}"
)
