name: General Issue
description: Report an issue you are facing reagrding this project
title: "[ISSUE]: <short title>"

labels: ["other"]
assignees: [""]


body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if a similar issue already exists.
    options:
    - label: I have searched the existing issues and confirm this is a new issue.
      required: true

- type: textarea
  attributes:
    label: Issue
    description: Descrbe the issue.
  validations:
    required: true

- type: textarea
  attributes:
    label: Suggestions
    description: How do you want this issue to be resolved ?
    render: markdown
  validations:
    required: false

- type: textarea
  attributes:
    label: Context
    description: |
      Any important information that can help resolve your issue or provide context.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

- type: checkboxes
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Ogoruwa/clipt/).
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
