# https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml

name: CMake CI/CD
permissions:
  contents: read

on:
  push:
    branches: [ main, dev ]
    paths:
      - "**.c"
      - "**.h"
      - CMakeLists.txt
      - .github/workflows/cmake.yml

  pull_request:
    branches: [ main, dev ]
    paths:
      - "**.c"
      - "**.h"
      - CMakeLists.txt
      - .github/workflows/cmake.yml

jobs:
  CI_CD:
    name: Cmake CI/CD
    runs-on: ${{matrix.os}}

    env:
      IS_MAIN_BRANCH: ${{ (github.event_name == 'push' && github.head_ref == 'main') ||  github.ref_name == 'main'  }}
      BUILD_DIR: ${{github.workspace}}/build
      ARTIFACT_NAME: CLipt-${{matrix.os}}-${{matrix.c_compiler}}-${{matrix.build_type}}
      REPL_EXECUTABLE: ${{github.workspace}}/build/bin/${{matrix.build_type}}/cliptr
      TEST_EXECUTABLE: ${{github.workspace}}/build/bin/${{matrix.build_type}}/test_suite

    strategy:
      fail-fast: false
      max-parallel: 3

      matrix:
        os: [windows-latest]
        build_type: [Debug]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
          # - os: ubuntu-latest
          #   c_compiler: gcc
          # - os: ubuntu-latest
          #   c_compiler: clang
          # - os: macos-latest
          #   c_compiler: gcc
          # - os: macos-latest
          #   c_compiler: clang
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
          - os: macos-latest
            c_compiler: cl

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4


    - name: Setup
      # Turn repeated input strings (such as the build output directory) into step outputs.
      # These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        mkdir -p "${{github.workspace}}/build/logs"


    - name: Extra setup (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "Nothing to do here"


    - name: Extra setup (Windows)
      # Visual Studio folder added to path so executables can find clang_rt.asan dll
      # Windows kits folder added to path so executables can find ucrt dll
      if: runner.os == 'Windows'
      run: |
        mkdir -p "${{env.BUILD_DIR}}/logs/DrMemory" > $null
        echo "C:\Program Files (x86)\Dr. Memory\bin" >> $env:GITHUB_PATH
        echo "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\ucrt" >> $env:GITHUB_PATH
        echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64" >> $env:GITHUB_PATH


    - name: Extra setup (MacOS)
      if: runner.os == 'macOS'
      # Install clang-tidy
      run: |
        brew install llvm
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH


    - name: Configure CMake
      id: configure
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required
      # if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      # -DCMAKE_C_FLAGS="-fsanitize=address -fno-omit-frame-pointer"
      run: >
        cmake -S ${{github.workspace}} -B ${{env.BUILD_DIR}}
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DCMAKE_C_COMPILER=${{matrix.c_compiler}}
        -DENABLE_CLANG_TIDY=ON -DCLANG_TIDY_WARNINGS_AS_ERRORS=${{((env.IS_MAIN_BRANCH == 'true') && 'ON') || 'OFF'}}
        -DENABLE_ASAN=ON


    - name: Build
      id: build
      # Build your program with the given configuration. Note that --config is needed because
      # the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{env.BUILD_DIR}} --config ${{matrix.build_type}}


    - name: Test
      id: test
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because
      # the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      working-directory: ${{env.BUILD_DIR}}
      run: |
        ctest --verbose --output-on-failure --build-config ${{matrix.build_type}}


    - name: Pack
      id: pack
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cpack -C ${{matrix.build_type}}


    - name: Debug build directory
      if: ${{ always() && (steps.pack.outcome == 'failure' || steps.test.outcome == 'failure' || steps.build.outcome == 'failure') }}
      working-directory: ${{env.BUILD_DIR}}
      run: |
        echo -e "\nPath: ${{runner.os == 'Windows' && '$env:PATH' || '$PATH'}}\n"
        ls
        ls -R "bin"
        ls -R "lib"
        ls -R "Testing"
        ls -R "Packaging"


    - name: Upload build artifacts
      # Upload packaged files
      if: ${{ always() && steps.pack.outcome == 'success' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.ARTIFACT_NAME}}
        path: ${{env.BUILD_DIR}}/Packaging/*.*
        retention-days: 7
        if-no-files-found: error


    # Run memory leak tests
    - name: Install Valgrind (Linux) or DrMemory (Windows)
      uses: ConorMacBride/install-package@v1
      with:
        apt: valgrind
        choco: drmemory

    - name: Run memory leak tests (Linux)
      working-directory: ${{env.BUILD_DIR}}
      if: runner.os == 'Linux'
      run: |
        valgrind --leak-check=full --show-leak-kinds=all -s ctest --build-config ${{matrix.build_type}}

    - name: Run memory leak tests (MacOS)
      working-directory: ${{env.BUILD_DIR}}
      if: runner.os == 'macOS'
      run: |
        MallocStackLogging=1 leaks -atExit -- ctest --build-config ${{matrix.build_type}}

    - name: Run memory leak tests (Windows)
      working-directory: ${{env.BUILD_DIR}}
      if: runner.os == 'Windows'
      #drmemory -batch -leaks_only -logdir ${{env.BUILD_DIR}}/logs -- ctest --build-config ${{matrix.build_type}}
      run: |
        drmemory -verbose 2 -leaks_only -no_count_leaks -no_track_allocs -logdir ${{env.BUILD_DIR}}/logs/DrMemory -- ctest --build-config ${{matrix.build_type}}
        echo "\n\nDrMemory Logs: \n"
        cat ${{env.BUILD_DIR}}/logs/DrMemory/DrMemory-*
