name: Documentation

on:
  push:
    tags:
      - "*"
    branches: [ main ]

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Docs
      run: |
        sudo apt-get install doxygen
    - name: setup
      run: |
        sudo apt-get install cmake
    - name: configure
      run: |
        cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
    - name: build
      run: |
        cmake --build build --config Debug --target docs -j4
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        build_dir: ./docs/html
