name: Ubuntu CI Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt-get install cmake
    - name: configure
      run: |
        cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
    - name: build
      run: |
        cmake --build build --config Debug --target TestSuite -j4
    - name: test
      run: |
        cd build
        ctest
        bash <(curl -s https://codecov.io/bash)
    - name: pack
      run: |
        cpack
