name: Windows CI Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        choco install cmake
    - name: configure
      run: |
        cmake -S . -B build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE="Debug"
    - name: build
      run: |
        cmake --build build --config Debug --target TestSuite -j4
    - name: test
      run: |
        cd build
        ctest
    - name: pack
      run: |
        cpack
